name: Spring PetClinic CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-test-docker:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Build and Test
      run: |
        cd spring-petclinic
        mvn clean verify


    - name: Build Docker Image
      run: |
        cd spring-petclinic
        docker build -t petclinic .