name: Spring PetClinic CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-docker-ecr:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Build and Test
      run: |
        cd spring-petclinic
        mvn clean verify


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3


    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build Docker image
      run: |
        cd spring-petclinic
        docker build -t spring-petclinic .


    - name: Push image to ECR
      run: |
        docker tag spring-petclinic:latest 676591241595.dkr.ecr.eu-west-3.amazonaws.com/spring-petclinic:latest
        docker push 676591241595.dkr.ecr.eu-west-3.amazonaws.com/spring-petclinic:latest