name: Spring PetClinic CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd spring-petclinic
        mvn clean verify